<!DOCTYPE html>
<html>
<body>
	<section class="regular slider">
	<div class="item"><img src="https://placeimg.com/640/480/tech"/></div>
            <div class="item"><img src="https://placeimg.com/640/480/tech"/></div>
            <div class="item"><img src="https://placeimg.com/640/480/animal"/></div>
            <div class="item"><img src="https://placeimg.com/640/480/tree"/></div>
            <div class="item"><img src="https://placeimg.com/640/480/world"/></div>
            <div class="item"><img src="https://placeimg.com/640/480/tech"/></div>
            <div class="item"><img src="https://placeimg.com/640/480/tech"/></div>
            <div class="item"><img src="https://placeimg.com/640/480/tech"/></div>
            
	</section>
</body>
</html>